import { request } from '@/utils'
export default {
  getJobById: (id) => request.get(`/recruitment/getByID/${id}`),
  update: (data) => request.put(`/recruitment/update`, data),
  uploadEmployee: (userId, data) => request.post(`/employee/upload/${userId}`, data),
  getByUserId: (userId) => request.get(`/employee/getByUserId/${userId}`),
  getAll: () => request.get('/employee/getAll'),
  jobrec: (data, params = {}) => request.post('/recruitment/recommend', data, {params}),
  seekerrec: (id)=> request.get(`/employee/recommend/${id}`),
  addHistory:(userId,recruitmentId) => request.post(`/user/history/${userId}/${recruitmentId}`),
  addFavorites:(userId,recruitmentId) => request.post(`/user/favorites/${userId}/${recruitmentId}`),
  deleteFavorites:(userId,recruitmentId) => request.delete(`/user/favorites/${userId}/${recruitmentId}`),
  isFavorites:(userId,recruitmentId) => request.get(`/user/favorites/${userId}/${recruitmentId}`),
  addApplications:(userId,recruitmentId) => request.post(`/user/applications/${userId}/${recruitmentId}`),
  deleteApplications:(userId,recruitmentId) => request.delete(`/user/applications/${userId}/${recruitmentId}`),
  isApplications:(userId,recruitmentId) => request.get(`/user/applications/${userId}/${recruitmentId}`),
  getWinners:(recruitmentId) => request.get(`/user/winners/${recruitmentId}`),
  getFavoritesSeeker:(recruitmentId) => request.get(`/user/favorites2/${recruitmentId}`),
  getApplicationsSeeker:(recruitmentId) => request.get(`/user/offers2/${recruitmentId}`),
  distributeOffer:(userId, recruitmentId) => request.put(`/user/offers/${userId}/${recruitmentId}`),
  cancelOffer:(userId, recruitmentId) => request.put(`/user/cancelOffers/${userId}/${recruitmentId}`),
  isDistributeOffer:(userId, recruitmentId) => request.get(`/user/offers/${userId}/${recruitmentId}`),
  addFavoritesRecruitment:(userId,recruitmentId) => request.post(`/recruitment/favorites/${userId}/${recruitmentId}`),
  deleteFavoritesRecruitment:(userId,recruitmentId) => request.delete(`/recruitment/favorites/${userId}/${recruitmentId}`),
  getFavoritesRecruitment:(recruitmentId) => request.get(`/recruitment/favorites/${recruitmentId}`),
  isFavoritesRecruitment:(userId,recruitmentId) => request.get(`/recruitment/favorites/${userId}/${recruitmentId}`),
}
